services:
  - type: web
    name: securechat
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 -p $PORT securechat_backend.asgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.7
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        sync: false
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: securechat-db
          property: connectionString

databases:
  - name: securechat-db
    databaseName: securechat
    user: securechat
